# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui',
# licensing of 'main_window.ui' applies.
#
# Created: Wed May 29 08:27:33 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(549, 430)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget.setAcceptDrops(False)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.question = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Bamum")
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.question.setFont(font)
        self.question.setObjectName("question")
        self.verticalLayout_4.addWidget(self.question)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.groupBox.setPalette(palette)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setTitle("")
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_classfifier = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_classfifier.setEnabled(True)
        self.radioButton_classfifier.setChecked(True)
        self.radioButton_classfifier.setAutoExclusive(True)
        self.radioButton_classfifier.setObjectName("radioButton_classfifier")
        self.verticalLayout.addWidget(self.radioButton_classfifier)
        self.radioButton_regression = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_regression.setAutoFillBackground(False)
        self.radioButton_regression.setObjectName("radioButton_regression")
        self.verticalLayout.addWidget(self.radioButton_regression)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.line.setFont(font)
        self.line.setMouseTracking(False)
        self.line.setAutoFillBackground(True)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_quiz = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_quiz.setChecked(True)
        self.radioButton_quiz.setObjectName("radioButton_quiz")
        self.verticalLayout_2.addWidget(self.radioButton_quiz)
        self.radioButton_data = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_data.setObjectName("radioButton_data")
        self.verticalLayout_2.addWidget(self.radioButton_data)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setObjectName("pushButton_start")
        self.verticalLayout_4.addWidget(self.pushButton_start)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.question.setText(QtWidgets.QApplication.translate("MainWindow", "What method do you want to choose?", None, -1))
        self.radioButton_classfifier.setText(QtWidgets.QApplication.translate("MainWindow", "Classifier", None, -1))
        self.radioButton_regression.setText(QtWidgets.QApplication.translate("MainWindow", "Regression", None, -1))
        self.radioButton_quiz.setText(QtWidgets.QApplication.translate("MainWindow", "Pass the quiz", None, -1))
        self.radioButton_data.setText(QtWidgets.QApplication.translate("MainWindow", "Predict diagnosis by data", None, -1))
        self.pushButton_start.setText(QtWidgets.QApplication.translate("MainWindow", "Get started", None, -1))

